// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Entities;

namespace api.Entities.Migrations
{
    [DbContext(typeof(PlaDatContext))]
    [Migration("20201202150637_removeExplicitPlacementStudent")]
    partial class removeExplicitPlacementStudent
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CapabilityPlacement", b =>
                {
                    b.Property<int>("CapabilitiesId")
                        .HasColumnType("int");

                    b.Property<int>("PlacementsId")
                        .HasColumnType("int");

                    b.HasKey("CapabilitiesId", "PlacementsId");

                    b.HasIndex("PlacementsId");

                    b.ToTable("CapabilityPlacement");
                });

            modelBuilder.Entity("CapabilityStudent", b =>
                {
                    b.Property<int>("CapabilitiesId")
                        .HasColumnType("int");

                    b.Property<int>("StudentsId")
                        .HasColumnType("int");

                    b.HasKey("CapabilitiesId", "StudentsId");

                    b.HasIndex("StudentsId");

                    b.ToTable("CapabilityStudent");
                });

            modelBuilder.Entity("PlacementStudent", b =>
                {
                    b.Property<int>("PlacementsId")
                        .HasColumnType("int");

                    b.Property<int>("StudentsId")
                        .HasColumnType("int");

                    b.HasKey("PlacementsId", "StudentsId");

                    b.HasIndex("StudentsId");

                    b.ToTable("PlacementStudent");
                });

            modelBuilder.Entity("api.Entities.Capability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Capabilities");
                });

            modelBuilder.Entity("api.Entities.Employer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CompanyDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Employers");
                });

            modelBuilder.Entity("api.Entities.Placement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("EmployerCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("PlacementImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployerCompanyId");

                    b.ToTable("Placements");
                });

            modelBuilder.Entity("api.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CapabilityPlacement", b =>
                {
                    b.HasOne("api.Entities.Capability", null)
                        .WithMany()
                        .HasForeignKey("CapabilitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Entities.Placement", null)
                        .WithMany()
                        .HasForeignKey("PlacementsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CapabilityStudent", b =>
                {
                    b.HasOne("api.Entities.Capability", null)
                        .WithMany()
                        .HasForeignKey("CapabilitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlacementStudent", b =>
                {
                    b.HasOne("api.Entities.Placement", null)
                        .WithMany()
                        .HasForeignKey("PlacementsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Entities.Placement", b =>
                {
                    b.HasOne("api.Entities.Employer", "EmployerCompany")
                        .WithMany()
                        .HasForeignKey("EmployerCompanyId");

                    b.Navigation("EmployerCompany");
                });
#pragma warning restore 612, 618
        }
    }
}
